language: node_js
node_js:
- 10
install:
- npm install
- npm install -g firebase-tools
script:
- npm run test:unit
after_success:
- npm run build
deploy:
  provider: firebase
  token:
    secure: 0kQSgGwKT39sCcLwwDbcT81kc0ICkfoZcDWdeey58d3LXj8AvCtsb4AFh6uCOpzBW54LA9isqLrYIzUgfNtM1NWALTl4Y4qTqx5z4tzmJzJM+FAc+yBjgFcd+gI1UG7QKmyxgYRcoRUMOXTXDAWRgSppXxRJEEbnuoC3RW7bUACN27IkD4HX8KrvWbHYFEn4aBBdmlo+IRI+kJdN/Xr/Th/UtfXV6+revWmf9JY4W4hdTIbHDgB+hsAQaIcf4cvXtKbJQED/ueLz/Wkix/zQb3e07b73GBqT4PXemZgBmWio35PNY/mq7KONtHhhL6W44EedlRajUQE6td+vZtHnGB0jAXFKfiQeTIOp5mhbwZ5ChHISN9Al2N6vS/b+3p7AtjGX06SgYIAUqUPtziy30C/n/sc2M5GUG3yXcCYrL06k/mWlVc8huLENUkIkg5lQVo1RGA4fGxhV4TuAA02BahXfdtxYrL1iJ0hwmsAZSCxjqrNtOnFNJI+i04mZd1WZl36nabu/vA2vEfCr1ZQsBiXSApK4TvTfOhAm2N/YOrlvn1CW9vQL/N5Hat0UT2DAFiUlau4bQenIYG6TMGZsx8A0frDZutXXYHyiXDqZIbyt8nVrajM9ckhVUQ+09cwOlpcLxzJnGpOg1h987RCEqSOiPJwrds0ITfkKJvLggLo=
env:
  global:
    secure: 0kQSgGwKT39sCcLwwDbcT81kc0ICkfoZcDWdeey58d3LXj8AvCtsb4AFh6uCOpzBW54LA9isqLrYIzUgfNtM1NWALTl4Y4qTqx5z4tzmJzJM+FAc+yBjgFcd+gI1UG7QKmyxgYRcoRUMOXTXDAWRgSppXxRJEEbnuoC3RW7bUACN27IkD4HX8KrvWbHYFEn4aBBdmlo+IRI+kJdN/Xr/Th/UtfXV6+revWmf9JY4W4hdTIbHDgB+hsAQaIcf4cvXtKbJQED/ueLz/Wkix/zQb3e07b73GBqT4PXemZgBmWio35PNY/mq7KONtHhhL6W44EedlRajUQE6td+vZtHnGB0jAXFKfiQeTIOp5mhbwZ5ChHISN9Al2N6vS/b+3p7AtjGX06SgYIAUqUPtziy30C/n/sc2M5GUG3yXcCYrL06k/mWlVc8huLENUkIkg5lQVo1RGA4fGxhV4TuAA02BahXfdtxYrL1iJ0hwmsAZSCxjqrNtOnFNJI+i04mZd1WZl36nabu/vA2vEfCr1ZQsBiXSApK4TvTfOhAm2N/YOrlvn1CW9vQL/N5Hat0UT2DAFiUlau4bQenIYG6TMGZsx8A0frDZutXXYHyiXDqZIbyt8nVrajM9ckhVUQ+09cwOlpcLxzJnGpOg1h987RCEqSOiPJwrds0ITfkKJvLggLo=
