language: node_js

node_js:
  - 10

install:
  - npm install
  - npm install -g firebase-tools

script:
  - npm run test:unit

after_success:
  - npm run build
  - firebase deploy --token $FIREBASE_TOKEN